# Generated by Django 4.0.1 on 2022-09-14 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('acc_type', models.CharField(blank=True, choices=[('M', 'Malkia'), ('R', 'Salary'), ('S', 'Savings'), ('T', 'Tanzanite'), ('J', 'Junior'), ('A', 'Scholar'), ('F', 'Fixed'), ('D', 'Dhahabu')], max_length=100, null=True)),
                ('account_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
