# Generated by Django 4.0.1 on 2022-09-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('acc_type', models.CharField(blank=True, choices=[('M', 'Malkia'), ('R', 'Salary'), ('S', 'Savings'), ('T', 'Tanzanite'), ('J', 'Junior'), ('A', 'Scholar'), ('F', 'Fixed'), ('D', 'Dhahabu')], max_length=100, null=True)),
            ],
        ),
    ]
