# Generated by Django 4.0.1 on 2022-08-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0003_remove_customer_nida_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['account_name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='acc_type',
            field=models.CharField(blank=True, choices=[('M', 'Malkia'), ('R', 'Salary'), ('S', 'Savings'), ('T', 'Tanzanite'), ('J', 'Junior'), ('A', 'Scholar'), ('F', 'Fixed'), ('D', 'Dhahabu')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
