# Generated by Django 4.0.1 on 2022-09-01 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0004_alter_customer_options_customer_acc_type_and_more'),
        ('depo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='account',
        ),
        migrations.AddField(
            model_name='deposit',
            name='my_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cust.customer'),
        ),
    ]
